backend:
  name: github
  repo: nevanscott/notated.org
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "links"
    label: "Links"
    folder: "_source/_links/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DDTHH:mm:ssZ",
        }
      - { label: "Source URL", name: "source", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    view_groups:
      - label: Year
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
  - name: "blog"
    label: "Blog"
    folder: "_source/_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DDTHH:mm:ssZ",
        }
      - { label: "Body", name: "body", widget: "markdown" }
