markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - footnotes
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
prose:
  siteurl: http://dev.notated.org
  media: assets/uploads
  metadata:
    _posts:
      -
        name: title
        field:
          element: text
          label: title
    linked/_posts:
      -
        name: title
        field:
          element: text
          label: title
      -
        name: ext
        field:
          element: text
          label: URL