name: Notated
tagline: notes on learning, design, & life
url: https://notated.org
author: Nevan Scott
source: _source

permalink: /:title/

pagination:
  enabled: true
  permalink: /:num/

plugins:
  - jekyll-paginate-v2

collections:
  links:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:year/:month/:title/
  - scope:
      path: "_links"
    values:
      layout: "post"
      permalink: /:year/:month/:title/

timezone: Europe/Madrid
